all: assignv1-template

assignv1-template: assignv1-template.c
	gcc -o assignv1-template assignv1-template.c
	sudo cp assignv1-template /bin
	cd /bin
	sudo chmod +x assignv1-template
	cd -
	rm assignv1-template
