assignv1-template: assignv1-template.c
	gcc -o assignv1-template assignv1-template.c
	sudo cp assignv1-template /bin
	sudo chmod +x /bin/assignv1-template
	cd && echo 'export PATH=$$PATH:/bin/assignv1-template' >> .bashrc
	rm assignv1-template
	@echo "Restart your terminal to see the binary file."

notesv1-template: notesv1-template.c
	gcc -o notesv1-template notesv1-template.c
	sudo cp notesv1-template /bin
	sudo chmod +x /bin/notesv1-template
	cd && echo 'export PATH=$$PATH:/bin/notesv1-template' >> .bashrc
	rm notesv1-template
	@echo "Restart your terminal to see the binary file."
